# Generated by Django 3.2.7 on 2021-09-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='skill',
            field=models.IntegerField(choices=[(1, 'a'), (2, 'b'), (3, 'c'), (4, 'd')]),
        ),
    ]
