# Generated by Django 3.2.7 on 2021-09-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210912_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='sexa',
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.IntegerField(choices=[(1, 'ชาย'), (2, 'หญิง')]),
        ),
    ]
