# Generated by Django 3.2.7 on 2021-09-11 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_patient_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='hospital',
            field=models.ForeignKey(default='ไม่มี', on_delete=django.db.models.deletion.CASCADE, to='app.hospital'),
        ),
    ]
